### ISSUE TITLE
Add instructions for Hyper-V Support

### ISSUE THREAD

**Issue by jet082** [Andoryuuta/Erupe#34]
If you have Hyper-V support (for example if you are running wsl2), the ports used by Erupe conflict with the ones reserved by default by Hyper-V.

To fix this issue, do the following:

```
dism.exe /Online /Disable-Feature:Microsoft-Hyper-V
<Reboot>
netsh int ipv4 add excludedportrange protocol=tcp startport=53310 numberofports=1
netsh int ipv4 add excludedportrange protocol=tcp startport=53312 numberofports=1
netsh int ipv4 add excludedportrange protocol=tcp startport=54001 numberofports=1
dism.exe /Online /Enable-Feature:Microsoft-Hyper-V
<Reboot>
```

Then both Hyper-V and Erupe can co-exist.

**Comment by Andoryuuta** [comment]
I can definitely add a note to the readme pointing to this issue for people with port binding issues. However, these are not standard ports that Hyper-V / wsl2 should be reserving. The general consensus online is that this only happens due to faulty windows updates.

I have Hyper-V & wsl2 running without any conflicts with Erupe.

See:
https://github.com/docker/for-win/issues/3171
https://github.com/microsoft/WSL/issues/5514
https://github.com/dotnet/aspnetcore/issues/25562
https://stackoverflow.com/questions/48478869/cannot-bind-to-some-ports-due-to-permission-denied/62061654#62061654

I'd be curious to know what the following command outputs on your machine:
`netsh int ipv4 show excludedportrange protocol=tcp`

**Comment by jet082** [comment]
Originally, that command had listed a huge range of ports. After following the instructions I posted, they were fixed.

Here it is now...

```
PS C:\WINDOWS\system32> netsh int ipv4 show excludedportrange protocol=tcp

Protocol tcp Port Exclusion Ranges

Start Port    End Port
----------    --------
      5426        5426
     28385       28385
     28390       28390
     49759       49858
     49859       49958
     50000       50059     *
     50060       50159
     50160       50259
     50260       50359
     50360       50459
     50831       50930
     51309       51408
     51409       51508
     51509       51608
     51609       51708
     51709       51808
     51809       51908
     51909       52008
     53310       53310     *
     53312       53312     *
     54001       54001     *
     54235       54235
     54236       54236

* - Administered port exclusions.
```

**Comment by Andoryuuta** [comment]
Interesting.

I very recently installed Window 10 + wsl2 + hyper-v and mine looks like this:
```
PS C:\WINDOWS\system32> netsh int ipv4 show excludedportrange protocol=tcp

Protocol tcp Port Exclusion Ranges

Start Port    End Port
----------    --------
      1121        1220
      5357        5357
      5426        5426
      5768        5867
      6068        6167
     17149       17248
     17297       17396
     22023       22122
     28385       28385
     28390       28390
     50000       50059     *
     54235       54235
     54236       54236

* - Administered port exclusions.
```

I'll add a note to the README right now.
